# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/manolo/Embedded/openembedded-core/meta \
  /home/manolo/Embedded/meta-yocto/meta-poky \
  /home/manolo/Embedded/meta-yocto/meta-yocto-bsp \
  /home/manolo/Embedded/meta-openembedded/meta-oe \
  /home/manolo/Embedded/meta-openembedded/meta-python \
  /home/manolo/Embedded/meta-openembedded/meta-networking \
  /home/manolo/Embedded/meta-intel \
  /home/manolo/Embedded/meta-myboard \
  /home/manolo/Embedded/meta-qt6 \
  "
